import streamlit as st
import requests
import io
from PIL import Image

# Page Config
st.set_page_config(page_title="AI Image Generator", page_icon="🎨")

st.title("🎨 AI Image Generator")
st.write("Generate high-quality AI images from your text prompts.")

# User Input
prompt = st.text_input("Enter your creative prompt:", placeholder="Example: A futuristic city at night, cinematic lighting, 8k...")

if st.button("Generate Image"):
    if prompt:
        with st.spinner("Wait Ruka! AI is creating your masterpiece... 🖌️"):
            
            API_URL = "https://api-inference.huggingface.co/models/stabilityai/stable-diffusion-xl-base-1.0"
            headers = {"Authorization": f"Bearer {st.secrets['HF_TOKEN']}"}
            
            try:
                response = requests.post(API_URL, headers=headers, json={"inputs": prompt})
                
                if response.status_code == 200:
                    image_bytes = response.content
                    image = Image.open(io.BytesIO(image_bytes))
                    st.image(image, caption="Generated by Ruka's AI", use_column_width=True)
                    
                    # Download Button
                    st.download_button(label="Download Image", data=image_bytes, file_name="ai_image.png", mime="image/png")
                    st.success("Boooooooooooooooom! Your image is ready!")
                else:
                    st.error(f"Error: {response.status_code}. The API might be busy. Please try a different prompt or wait a moment.")
            except Exception as e:
                st.error(f"An error occurred: {e}")
    else:
        st.warning("Please enter a prompt first!")

st.markdown("---")
st.caption("Developed by Rukshan Weerasekara")
